# Generated by Django 6.0.5 on 2026-05-25 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=32)),
                ('fuel_type', models.CharField(blank=True, max_length=32, null=True)),
                ('grid_region', models.CharField(blank=True, max_length=32, null=True)),
                ('transport_mode', models.CharField(blank=True, max_length=32, null=True)),
                ('factor_value', models.FloatField()),
                ('unit', models.CharField(max_length=16)),
                ('source', models.CharField(max_length=64)),
                ('valid_from', models.IntegerField()),
                ('valid_to', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_unit', models.CharField(max_length=16)),
                ('to_unit', models.CharField(max_length=16)),
                ('conversion_factor', models.FloatField()),
                ('source_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DataIngestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility'), ('travel', 'Travel')], max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('activity_type', models.CharField(max_length=32)),
                ('activity_value', models.FloatField()),
                ('activity_unit', models.CharField(max_length=16)),
                ('emission_factor', models.FloatField()),
                ('emission_factor_source', models.CharField(max_length=64)),
                ('co2e_kg', models.FloatField()),
                ('facility', models.CharField(blank=True, max_length=128, null=True)),
                ('location', models.CharField(blank=True, max_length=128, null=True)),
                ('reporting_period', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('flagged', 'Flagged'), ('approved', 'Approved'), ('locked', 'Locked')], default='pending', max_length=16)),
                ('flagged_reason', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='DataQualityFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('outlier', 'Outlier'), ('unit_mismatch', 'Unit Mismatch'), ('gap', 'Gap'), ('duplicate', 'Duplicate')], max_length=32)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('error', 'Error')], max_length=16)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.normalizedrecord')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('field_name', models.CharField(max_length=64)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.normalizedrecord')),
            ],
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataingestion')),
            ],
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='raw_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rawrecord'),
        ),
    ]
