# Generated by Django 6.0.5 on 2026-05-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedrecord',
            name='edit_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
