# Generated by Django 6.0.5 on 2026-05-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_normalizedrecord_edit_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionfactor',
            name='unit',
            field=models.CharField(max_length=32),
        ),
    ]
